// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator.CSharp.CodeFixes
{
    public static partial class CodeFixIdentifiers
    {
        public const string RemoveUnusedVariable = Prefix + "0219";
    }
}